version: '3.1'

services:
  database:
    image: mariadb
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    volumes:
      - ./data/db:/var/lib/mysql
    ports:
      - 2336:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=database
      - PMA_PORT=3306
    ports:
      - 2380:80

  git-server:
    image: gogs/gogs:latest
    ports:
      - "9022:22"
      - "9000:3000"
    restart: always
    environment:
       - RUN_CROND=true
    volumes:
      - ./data/git:/data

  jenkin:
    image: jenkins
    build: ./jenkins
    ports:
      - "18080:8080"
      - "50000:50000"
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins_home:/var/jenkins_home

  

