version: '3.1'

services:
  database:
    image: mariadb
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    volumes:
      - ./data/db:/var/lib/mysql
    ports:
      - 2336:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=database
      - PMA_PORT=3306
    ports:
      - 2380:80

  git-server:
    image: gogs/gogs:latest
    ports:
      - "9022:22"
      - "9000:3000"
    restart: always
    environment:
       - RUN_CROND=true
    volumes:
      - ./data/git:/data

  jenkin:
    image: jenkins
    build: ./jenkins
    ports:
      - "18080:8080"
      - "50000:50000"
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins_home:/var/jenkins_home

  

  

  























# services:
#   drone-server:
#     image: drone/drone:0.8
#     ports:
#       - 4000:8000
#       # - 80:80
#       # - 443:443
#     networks: 
#       - git-server
#     volumes:
#       - ./drone:/var/lib/drone/
#     restart: always
#     environment:
#       - DRONE_OPEN=true
#       - DRONE_HOST=http://localhost:4000
#       - DRONE_SECRET=hello@world

#       # - DRONE_GITHUB=true
#       - DRONE_GITHUB_CLIENT=fa2c2ca2cb59e5c3d911
#       - DRONE_GITHUB_SECRET=c77803e4a79d6c330ad72c40688ad80421923b16
      
#       # - DRONE_BITBUCKET=true
#       - DRONE_BITBUCKET_CLIENT=QznDTtT46SLMezkzKt
#       - DRONE_BITBUCKET_SECRET=SbyjjwC2yLke2rGqax8rkMmAW4Hmdx8V

#       - DRONE_GOGS=true
#       - DRONE_GOGS_URL=http://git-server:3000
#       - DRONE_GOGS_GIT_USERNAME=quangthinh
#       - DRONE_GOGS_GIT_PASSWORD=123456
#       # - DRONE_LETS_ENCRYPT=true

#   drone-agent:
#     image: drone/agent:0.8
#     command: agent
#     restart: always
#     depends_on:
#       - drone-server
#     volumes:
#       - /var/run/docker.sock:/var/run/docker.sock

#     environment:
#       - DRONE_SERVER=drone-server:9000
#       - DRONE_SECRET=hello@world
#       - DRONE_HOST=http://localhost:4000
#     networks: 
#       - git-server

#   # git server
#   git-server:
#     image: gogs/gogs:latest
#     ports:
#       - "9022:22"
#       - "9000:3000"
#     restart: always
#     environment:
#        - RUN_CROND=true
#     volumes:
#       - ./gogs/data:/data
#     networks: 
#       - git-server

# networks: 
#   git-server:
#     driver: bridge
